// ============================================================================
// lib/data.ts — NusaBeras
// Data riil 34 provinsi dari output DSS (output_dss.csv).
// Seluruh interface & helper dipertahankan agar kompatibel dengan komponen
// yang sudah ada (DashboardContent, NationalSummaryContent, ProvinceDetailPanel,
// IndonesiaMap, PriceChart).
// ============================================================================

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Status = "surplus" | "stabil" | "defisit"
export type Kluster = "A" | "B" | "C" | "D"
export type ShapeTrajectory = "stabil" | "late_surge" | "peak_awal"

export interface ProvinceData {
  id: string
  name: string
  status: Status

  // Harga
  currentPrice: number        // harga minggu ini (prediksi_12minggu[0])
  predictedPrice: number      // prediksi 12 minggu ke depan (prediksi_12minggu[11])
  prediksi12Minggu: number[]  // array 12 titik prediksi untuk grafik
  historicalPrices: number[]   // 2 titik historis sebelum periode prediksi

  // DSS fields
  kluster: Kluster
  perubahanKumulatifPct: number
  shapeTrajectory: ShapeTrajectory
  skorPrioritas: number
  pasarTerhubung: string[]

  // Rekomendasi
  recommendation: string          // alias rekomendasi_operasional (dipakai ProvinceDetailPanel)
  rekomendasiOperasional: string
  rekomendasiStruktural: string

  // Legacy fields — diisi dari df_karakteristik 2025 agar panel detail menampilkan produksi/konsumsi
  production: number
  consumption: number
}

// ---------------------------------------------------------------------------
// Style helpers
// ---------------------------------------------------------------------------

export const STATUS_STYLE: Record<
  Status,
  { fill: string; hover: string; label: string; badge: string }
> = {
  surplus: {
    fill: "#16a34a",
    hover: "#15803d",
    label: "Surplus",
    badge: "border-emerald-300 bg-emerald-50 text-emerald-700",
  },
  stabil: {
    fill: "#2563eb",
    hover: "#1d4ed8",
    label: "Stabil",
    badge: "border-blue-300 bg-blue-50 text-blue-700",
  },
  defisit: {
    fill: "#dc2626",
    hover: "#b91c1c",
    label: "Defisit",
    badge: "border-red-300 bg-red-50 text-red-700",
  },
}

// ---------------------------------------------------------------------------
// Raw data — 34 provinsi
// ---------------------------------------------------------------------------

export const PROVINCES: ProvinceData[] = [
  {
    id: "aceh",
    name: "Aceh",
    kluster: "C",
    status: "stabil",
    currentPrice: 15155,
    predictedPrice: 15131,
    prediksi12Minggu: [15155,15160,15156,15153,15149,15145,15141,15138,15136,15134,15132,15131],
    historicalPrices: [15150,15150],
    perubahanKumulatifPct: -0.13,
    shapeTrajectory: "stabil",
    skorPrioritas: 0.0,
    pasarTerhubung: [],
    rekomendasiOperasional: "Harga beras di Aceh diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.49). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Aceh — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Aceh diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.49). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 1000.31,
    consumption: 671.56,
  },
  {
    id: "sumatera-utara",
    name: "Sumatera Utara",
    kluster: "D",
    status: "defisit",
    currentPrice: 14877,
    predictedPrice: 15189,
    prediksi12Minggu: [14877,14904,14932,14959,14986,15012,15040,15064,15090,15121,15155,15189],
    historicalPrices: [14800,14850],
    perubahanKumulatifPct: 2.29,
    shapeTrajectory: "late_surge",
    skorPrioritas: 11.747,
    pasarTerhubung: ["Riau", "Jambi"],
    rekomendasiOperasional: "Harga beras di Sumatera Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.91, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Riau dan Jambi saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Sumatera Utara — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Sumatera Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.91, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Riau dan Jambi saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 1564.06,
    consumption: 1710.75,
  },
  {
    id: "sumatera-barat",
    name: "Sumatera Barat",
    kluster: "C",
    status: "stabil",
    currentPrice: 18137,
    predictedPrice: 18004,
    prediksi12Minggu: [18137,18126,18115,18104,18089,18074,18060,18046,18033,18023,18014,18004],
    historicalPrices: [18150,18150],
    perubahanKumulatifPct: -0.80,
    shapeTrajectory: "stabil",
    skorPrioritas: 13.715,
    pasarTerhubung: ["Jambi", "Lampung"],
    rekomendasiOperasional: "Harga beras di Sumatera Barat diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.17). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Sumatera Barat — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Sumatera Barat diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.17). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 799.46,
    consumption: 682.47,
  },
  {
    id: "riau",
    name: "Riau",
    kluster: "D",
    status: "defisit",
    currentPrice: 16410,
    predictedPrice: 15983,
    prediksi12Minggu: [16410,16365,16323,16282,16240,16200,16162,16126,16091,16055,16020,15983],
    historicalPrices: [16450,16450],
    perubahanKumulatifPct: -2.84,
    shapeTrajectory: "stabil",
    skorPrioritas: 7.009,
    pasarTerhubung: ["DKI Jakarta", "Jambi"],
    rekomendasiOperasional: "Harga beras di Riau diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.21, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Jambi saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Riau memiliki konektivitas fisik dengan Sumatera Barat — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Sumatera Barat berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Riau diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.21, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Jambi saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 128.02,
    consumption: 606.1,
  },
  {
    id: "jambi",
    name: "Jambi",
    kluster: "D",
    status: "defisit",
    currentPrice: 15559,
    predictedPrice: 15674,
    prediksi12Minggu: [15559,15568,15578,15588,15599,15610,15621,15632,15643,15653,15664,15674],
    historicalPrices: [15550,15550],
    perubahanKumulatifPct: 0.79,
    shapeTrajectory: "late_surge",
    skorPrioritas: 7.523,
    pasarTerhubung: ["Sumatera Barat", "Lampung"],
    rekomendasiOperasional: "Harga beras di Jambi diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.65, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sumatera Barat dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Jambi — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Jambi diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.65, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sumatera Barat dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 210.65,
    consumption: 324.99,
  },
  {
    id: "sumatera-selatan",
    name: "Sumatera Selatan",
    kluster: "A",
    status: "surplus",
    currentPrice: 15930,
    predictedPrice: 16837,
    prediksi12Minggu: [15930,16011,16092,16170,16249,16329,16409,16491,16576,16663,16750,16837],
    historicalPrices: [15800,15850],
    perubahanKumulatifPct: 6.23,
    shapeTrajectory: "late_surge",
    skorPrioritas: 19.518,
    pasarTerhubung: ["Lampung"],
    rekomendasiOperasional: "Harga beras di Sumatera Selatan diprediksi naik 6.2% dalam 3 bulan ke depan, dengan tekanan yang diperkirakan memuncak menjelang akhir periode — respons pre-emptif diperlukan sebelum puncak terjadi. Produksi lokal masih mencukupi sebagian besar kebutuhan (surplus ratio 2.39), sehingga tekanan kemungkinan bersumber dari hambatan distribusi atau mekanisme pasar internal. Pasar Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Periksa apakah ada penumpukan stok di tingkat distributor. Percepat alur distribusi dari gudang ke pasar eceran dan koordinasikan dengan Bulog wilayah untuk memastikan rantai distribusi internal berjalan lancar. Dengan produksi yang mencukupi, pertimbangkan peran Sumatera Selatan sebagai penyuplai bagi provinsi defisit yang berdekatan — koordinasikan melalui jalur perdagangan aktif.",
    rekomendasiStruktural: "Sumatera Selatan memiliki surplus produksi 1.39 di atas kebutuhan lokal, namun harga beras justru mengalami tekanan kenaikan — indikasi kuat adanya disfungsi dalam tata niaga atau distribusi internal. Lakukan audit menyeluruh dari penggilingan hingga pasar eceran. Evaluasi kemungkinan penguasaan pasar yang tidak sehat oleh segelintir distributor besar, dan perkuat peran lembaga pangan lokal sebagai penyeimbang pasar.",
    recommendation: "Harga beras di Sumatera Selatan diprediksi naik 6.2% dalam 3 bulan ke depan, dengan tekanan yang diperkirakan memuncak menjelang akhir periode — respons pre-emptif diperlukan sebelum puncak terjadi. Produksi lokal masih mencukupi sebagian besar kebutuhan (surplus ratio 2.39), sehingga tekanan kemungkinan bersumber dari hambatan distribusi atau mekanisme pasar internal.",
    production: 2035.39,
    consumption: 853.18,
  },
  {
    id: "bengkulu",
    name: "Bengkulu",
    kluster: "D",
    status: "defisit",
    currentPrice: 15990,
    predictedPrice: 16510,
    prediksi12Minggu: [15990,16032,16075,16119,16164,16211,16261,16311,16361,16412,16462,16510],
    historicalPrices: [15950,15950],
    perubahanKumulatifPct: 3.51,
    shapeTrajectory: "late_surge",
    skorPrioritas: 10.809,
    pasarTerhubung: ["Sumatera Barat", "Lampung"],
    rekomendasiOperasional: "Harga beras di Bengkulu diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.73, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sumatera Barat dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Bengkulu memiliki konektivitas fisik dengan Sumatera Barat — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Sumatera Barat berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Bengkulu diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.73, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sumatera Barat dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 147.81,
    consumption: 203.49,
  },
  {
    id: "lampung",
    name: "Lampung",
    kluster: "C",
    status: "stabil",
    currentPrice: 14871,
    predictedPrice: 15110,
    prediksi12Minggu: [14871,14893,14915,14938,14959,14982,15004,15026,15047,15069,15090,15110],
    historicalPrices: [14850,14850],
    perubahanKumulatifPct: 1.75,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 16.588,
    pasarTerhubung: ["DKI Jakarta", "Sumatera Selatan"],
    rekomendasiOperasional: "Harga beras di Lampung diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 2.17). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Lampung — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Lampung diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 2.17). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 1822.45,
    consumption: 840.25,
  },
  {
    id: "kepulauan-bangka-belitung",
    name: "Kepulauan Bangka Belitung",
    kluster: "D",
    status: "defisit",
    currentPrice: 15247,
    predictedPrice: 14694,
    prediksi12Minggu: [15247,15195,15140,15085,15032,14981,14931,14885,14840,14792,14744,14694],
    historicalPrices: [15300,15300],
    perubahanKumulatifPct: -3.96,
    shapeTrajectory: "stabil",
    skorPrioritas: 12.234,
    pasarTerhubung: ["DKI Jakarta", "Lampung"],
    rekomendasiOperasional: "Harga beras di Kepulauan Bangka Belitung diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.26, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Kepulauan Bangka Belitung — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Kepulauan Bangka Belitung diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.26, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 38.72,
    consumption: 148.84,
  },
  {
    id: "kepulauan-riau",
    name: "Kepulauan Riau",
    kluster: "D",
    status: "defisit",
    currentPrice: 15528,
    predictedPrice: 15861,
    prediksi12Minggu: [15528,15557,15584,15613,15644,15675,15707,15738,15770,15801,15831,15861],
    historicalPrices: [15500,15500],
    perubahanKumulatifPct: 2.33,
    shapeTrajectory: "late_surge",
    skorPrioritas: 9.943,
    pasarTerhubung: ["DKI Jakarta", "Sumatera Barat"],
    rekomendasiOperasional: "Harga beras di Kepulauan Riau diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.00, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Sumatera Barat saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Kepulauan Riau memiliki konektivitas fisik dengan Lampung dan Jawa Timur — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Lampung dan Jawa Timur berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Kepulauan Riau diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.00, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Sumatera Barat saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 0.2,
    consumption: 202.56,
  },
  {
    id: "dki-jakarta",
    name: "DKI Jakarta",
    kluster: "D",
    status: "defisit",
    currentPrice: 16830,
    predictedPrice: 17174,
    prediksi12Minggu: [16830,16860,16891,16920,16952,16984,17017,17049,17082,17113,17144,17174],
    historicalPrices: [16800,16800],
    perubahanKumulatifPct: 2.22,
    shapeTrajectory: "late_surge",
    skorPrioritas: 7.425,
    pasarTerhubung: ["DI Yogyakarta", "Nusa Tenggara Barat"],
    rekomendasiOperasional: "Harga beras di DKI Jakarta diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.00, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DI Yogyakarta dan Nusa Tenggara Barat saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Rantai distribusi beras di DKI Jakarta lebih panjang dibanding median nasional (nilai 5.00). Petakan seluruh titik perantara dan identifikasi tahapan yang dapat dihilangkan. Fasilitasi skema kemitraan langsung antara penggilingan padi dan jaringan pengecer. Terapkan sistem informasi harga terbuka di tingkat pedagang grosir.",
    recommendation: "Harga beras di DKI Jakarta diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.00, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DI Yogyakarta dan Nusa Tenggara Barat saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 0.83,
    consumption: 1284.23,
  },
  {
    id: "jawa-barat",
    name: "Jawa Barat",
    kluster: "B",
    status: "stabil",
    currentPrice: 15228,
    predictedPrice: 16150,
    prediksi12Minggu: [15228,15308,15391,15474,15558,15642,15727,15812,15896,15981,16066,16150],
    historicalPrices: [15150,15150],
    perubahanKumulatifPct: 6.60,
    shapeTrajectory: "late_surge",
    skorPrioritas: 13.241,
    pasarTerhubung: ["DKI Jakarta", "Banten"],
    rekomendasiOperasional: "Harga beras di Jawa Barat diprediksi naik 6.6% dalam 3 bulan ke depan, dengan tekanan yang diperkirakan memuncak menjelang akhir periode — respons pre-emptif diperlukan sebelum puncak terjadi. Provinsi ini memiliki surplus ratio 0.92 — sebagian besar kebutuhan beras bergantung pada pasokan dari luar daerah. Pasar DKI Jakarta dan Banten saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Amankan komitmen pasokan dari provinsi pemasok utama dalam 2 minggu ke depan. Tetapkan ambang harga sebagai pemicu otomatis operasi pasar.",
    rekomendasiStruktural: "Jawa Barat — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Jawa Barat diprediksi naik 6.6% dalam 3 bulan ke depan, dengan tekanan yang diperkirakan memuncak menjelang akhir periode — respons pre-emptif diperlukan sebelum puncak terjadi. Provinsi ini memiliki surplus ratio 0.92 — sebagian besar kebutuhan beras bergantung pada pasokan dari luar daerah. Pasar DKI Jakarta dan Banten saat ini masih stabil. Amankan komitmen pasokan dari provinsi pemasok utama dalam 2 minggu ke depan. Tetapkan ambang harga sebagai pemicu otomatis operasi pasar.",
    production: 5777.44,
    consumption: 6259.75,
  },
  {
    id: "jawa-tengah",
    name: "Jawa Tengah",
    kluster: "C",
    status: "stabil",
    currentPrice: 15390,
    predictedPrice: 15912,
    prediksi12Minggu: [15390,15432,15475,15521,15572,15622,15671,15721,15770,15819,15866,15912],
    historicalPrices: [15350,15350],
    perubahanKumulatifPct: 3.66,
    shapeTrajectory: "late_surge",
    skorPrioritas: 12.994,
    pasarTerhubung: ["DI Yogyakarta", "Jawa Timur"],
    rekomendasiOperasional: "Harga beras di Jawa Tengah diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.33). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Jawa Tengah — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Jawa Tengah diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.33). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 5324.51,
    consumption: 4000.22,
  },
  {
    id: "di-yogyakarta",
    name: "DI Yogyakarta",
    kluster: "D",
    status: "defisit",
    currentPrice: 14240,
    predictedPrice: 14647,
    prediksi12Minggu: [14240,14278,14315,14353,14392,14430,14469,14507,14543,14579,14613,14647],
    historicalPrices: [14200,14200],
    perubahanKumulatifPct: 3.15,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 9.981,
    pasarTerhubung: ["Jawa Tengah", "Jawa Timur"],
    rekomendasiOperasional: "Harga beras di DI Yogyakarta diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.77, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Jawa Tengah dan Jawa Timur saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Rantai distribusi beras di DI Yogyakarta lebih panjang dibanding median nasional (nilai 5.00). Petakan seluruh titik perantara dan identifikasi tahapan yang dapat dihilangkan. Fasilitasi skema kemitraan langsung antara penggilingan padi dan jaringan pengecer. Terapkan sistem informasi harga terbuka di tingkat pedagang grosir.",
    recommendation: "Harga beras di DI Yogyakarta diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.77, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Jawa Tengah dan Jawa Timur saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 307.91,
    consumption: 398.86,
  },
  {
    id: "jawa-timur",
    name: "Jawa Timur",
    kluster: "C",
    status: "stabil",
    currentPrice: 14725,
    predictedPrice: 15027,
    prediksi12Minggu: [14725,14751,14778,14806,14835,14864,14893,14922,14950,14977,15003,15027],
    historicalPrices: [14700,14700],
    perubahanKumulatifPct: 2.23,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 17.189,
    pasarTerhubung: ["Jawa Tengah"],
    rekomendasiOperasional: "Harga beras di Jawa Timur diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.30). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Jawa Timur — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Jawa Timur diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.30). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 6004.97,
    consumption: 4610.13,
  },
  {
    id: "banten",
    name: "Banten",
    kluster: "D",
    status: "defisit",
    currentPrice: 15717,
    predictedPrice: 15713,
    prediksi12Minggu: [15717,15733,15744,15741,15736,15732,15725,15720,15716,15714,15713,15713],
    historicalPrices: [15700,15700],
    perubahanKumulatifPct: 0.09,
    shapeTrajectory: "stabil",
    skorPrioritas: 12.611,
    pasarTerhubung: ["DKI Jakarta", "Lampung"],
    rekomendasiOperasional: "Harga beras di Banten diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.81, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Banten memiliki konektivitas fisik dengan Lampung — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Lampung berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Banten diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.81, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Lampung saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 1009.69,
    consumption: 1251.11,
  },
  {
    id: "bali",
    name: "Bali",
    kluster: "D",
    status: "defisit",
    currentPrice: 15734,
    predictedPrice: 15581,
    prediksi12Minggu: [15734,15718,15703,15689,15676,15663,15650,15637,15623,15609,15595,15581],
    historicalPrices: [15750,15750],
    perubahanKumulatifPct: -1.07,
    shapeTrajectory: "stabil",
    skorPrioritas: 7.307,
    pasarTerhubung: ["Nusa Tenggara Barat", "Jawa Tengah"],
    rekomendasiOperasional: "Harga beras di Bali diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.61, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Nusa Tenggara Barat dan Jawa Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Bali memiliki konektivitas fisik dengan Nusa Tenggara Barat — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Nusa Tenggara Barat berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Bali diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.61, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Nusa Tenggara Barat dan Jawa Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 330.64,
    consumption: 543.17,
  },
  {
    id: "nusa-tenggara-barat",
    name: "Nusa Tenggara Barat",
    kluster: "C",
    status: "stabil",
    currentPrice: 13947,
    predictedPrice: 13886,
    prediksi12Minggu: [13947,13944,13942,13940,13939,13937,13934,13928,13921,13911,13900,13886],
    historicalPrices: [13950,13950],
    perubahanKumulatifPct: -0.46,
    shapeTrajectory: "stabil",
    skorPrioritas: 11.945,
    pasarTerhubung: ["Jawa Timur"],
    rekomendasiOperasional: "Harga beras di Nusa Tenggara Barat diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.34). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Nusa Tenggara Barat — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Nusa Tenggara Barat diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.34). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 958.13,
    consumption: 714.71,
  },
  {
    id: "nusa-tenggara-timur",
    name: "Nusa Tenggara Timur",
    kluster: "D",
    status: "defisit",
    currentPrice: 15329,
    predictedPrice: 15653,
    prediksi12Minggu: [15329,15353,15380,15411,15446,15481,15514,15546,15576,15603,15629,15653],
    historicalPrices: [15300,15300],
    perubahanKumulatifPct: 2.30,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 8.195,
    pasarTerhubung: ["Nusa Tenggara Barat", "Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Nusa Tenggara Timur diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.81, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Nusa Tenggara Barat dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Nusa Tenggara Timur memiliki konektivitas fisik dengan Jawa Timur dan Nusa Tenggara Barat — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Timur dan Nusa Tenggara Barat berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Nusa Tenggara Timur diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.81, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Nusa Tenggara Barat dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 553.65,
    consumption: 686.19,
  },
  {
    id: "kalimantan-barat",
    name: "Kalimantan Barat",
    kluster: "D",
    status: "defisit",
    currentPrice: 16637,
    predictedPrice: 16541,
    prediksi12Minggu: [16637,16624,16612,16603,16594,16586,16578,16570,16562,16555,16548,16541],
    historicalPrices: [16650,16650],
    perubahanKumulatifPct: -0.65,
    shapeTrajectory: "stabil",
    skorPrioritas: 12.404,
    pasarTerhubung: ["DKI Jakarta", "Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Kalimantan Barat diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.89, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Kalimantan Barat memiliki konektivitas fisik dengan Jawa Tengah — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Tengah berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Kalimantan Barat diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.89, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar DKI Jakarta dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 463.22,
    consumption: 519.57,
  },
  {
    id: "kalimantan-tengah",
    name: "Kalimantan Tengah",
    kluster: "D",
    status: "defisit",
    currentPrice: 19304,
    predictedPrice: 18781,
    prediksi12Minggu: [19304,19261,19219,19177,19135,19091,19045,18997,18946,18894,18839,18781],
    historicalPrices: [19300,19350],
    perubahanKumulatifPct: -2.94,
    shapeTrajectory: "stabil",
    skorPrioritas: 7.896,
    pasarTerhubung: ["Kalimantan Selatan", "Jawa Tengah"],
    rekomendasiOperasional: "Harga beras di Kalimantan Tengah diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.74, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Kalimantan Selatan dan Jawa Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Kalimantan Tengah memiliki konektivitas fisik dengan Jawa Tengah dan Jawa Timur — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Tengah dan Jawa Timur berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Kalimantan Tengah diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.74, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Kalimantan Selatan dan Jawa Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 197.57,
    consumption: 268.31,
  },
  {
    id: "kalimantan-selatan",
    name: "Kalimantan Selatan",
    kluster: "C",
    status: "stabil",
    currentPrice: 18863,
    predictedPrice: 18992,
    prediksi12Minggu: [18863,18877,18890,18903,18915,18927,18939,18950,18961,18972,18982,18992],
    historicalPrices: [18750,18850],
    perubahanKumulatifPct: 0.75,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 16.598,
    pasarTerhubung: ["Kalimantan Tengah", "Jawa Timur"],
    rekomendasiOperasional: "Harga beras di Kalimantan Selatan diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.52). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Kalimantan Selatan — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Kalimantan Selatan diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.52). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 681.22,
    consumption: 449.36,
  },
  {
    id: "kalimantan-timur",
    name: "Kalimantan Timur",
    kluster: "B",
    status: "stabil",
    currentPrice: 16280,
    predictedPrice: 17234,
    prediksi12Minggu: [16280,16361,16446,16531,16618,16704,16791,16879,16967,17056,17144,17234],
    historicalPrices: [16250,16200],
    perubahanKumulatifPct: 6.38,
    shapeTrajectory: "late_surge",
    skorPrioritas: 10.994,
    pasarTerhubung: ["Kalimantan Selatan", "Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Kalimantan Timur diprediksi naik 6.4% dalam 3 bulan ke depan, dengan tekanan yang diperkirakan memuncak menjelang akhir periode — respons pre-emptif diperlukan sebelum puncak terjadi. Provinsi ini memiliki surplus ratio 0.41 — sebagian besar kebutuhan beras bergantung pada pasokan dari luar daerah. Pasar Kalimantan Selatan dan Sulawesi Selatan saat ini masih stabil. Amankan komitmen pasokan dari provinsi pemasok utama dalam 2 minggu ke depan. Tetapkan ambang harga sebagai pemicu otomatis operasi pasar.",
    rekomendasiStruktural: "Kalimantan Timur memiliki konektivitas fisik dengan Jawa Timur dan Sulawesi Tengah — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Timur dan Sulawesi Tengah berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Kalimantan Timur diprediksi naik 6.4% dalam 3 bulan ke depan, dengan tekanan yang diperkirakan memuncak menjelang akhir periode — respons pre-emptif diperlukan sebelum puncak terjadi. Provinsi ini memiliki surplus ratio 0.41 — sebagian besar kebutuhan beras bergantung pada pasokan dari luar daerah. Pasar Kalimantan Selatan dan Sulawesi Selatan saat ini masih stabil. Amankan komitmen pasokan dari provinsi pemasok utama dalam 2 minggu ke depan. Tetapkan ambang harga sebagai pemicu otomatis operasi pasar.",
    production: 158.06,
    consumption: 381.84,
  },
  {
    id: "kalimantan-utara",
    name: "Kalimantan Utara",
    kluster: "D",
    status: "defisit",
    currentPrice: 17152,
    predictedPrice: 17688,
    prediksi12Minggu: [17152,17205,17258,17312,17364,17415,17464,17513,17559,17604,17647,17688],
    historicalPrices: [17050,17100],
    perubahanKumulatifPct: 3.44,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 14.324,
    pasarTerhubung: ["Kalimantan Timur", "Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Kalimantan Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.36, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Kalimantan Timur dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Kalimantan Utara memiliki konektivitas fisik dengan Jawa Timur dan Sulawesi Tengah — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Timur dan Sulawesi Tengah berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Kalimantan Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.36, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Kalimantan Timur dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 22.89,
    consumption: 64.18,
  },
  {
    id: "sulawesi-utara",
    name: "Sulawesi Utara",
    kluster: "D",
    status: "defisit",
    currentPrice: 15022,
    predictedPrice: 15233,
    prediksi12Minggu: [15022,15044,15065,15087,15108,15128,15147,15166,15184,15201,15217,15233],
    historicalPrices: [14950,15000],
    perubahanKumulatifPct: 1.55,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 9.383,
    pasarTerhubung: ["Gorontalo", "Sulawesi Tengah"],
    rekomendasiOperasional: "Harga beras di Sulawesi Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.50, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Gorontalo dan Sulawesi Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Sulawesi Utara memiliki konektivitas fisik dengan Sulawesi Tengah dan Sulawesi Selatan — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Sulawesi Tengah dan Sulawesi Selatan berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Sulawesi Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.50, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Gorontalo dan Sulawesi Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 150.34,
    consumption: 299.38,
  },
  {
    id: "sulawesi-tengah",
    name: "Sulawesi Tengah",
    kluster: "C",
    status: "stabil",
    currentPrice: 15298,
    predictedPrice: 14720,
    prediksi12Minggu: [15298,15251,15205,15156,15107,15056,15003,14949,14894,14837,14779,14720],
    historicalPrices: [15300,15350],
    perubahanKumulatifPct: -4.10,
    shapeTrajectory: "stabil",
    skorPrioritas: 8.236,
    pasarTerhubung: ["Sulawesi Barat", "Sulawesi Tenggara"],
    rekomendasiOperasional: "Harga beras di Sulawesi Tengah diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.42). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Sulawesi Tengah — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Sulawesi Tengah diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.42). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 528.38,
    consumption: 372.1,
  },
  {
    id: "sulawesi-selatan",
    name: "Sulawesi Selatan",
    kluster: "C",
    status: "stabil",
    currentPrice: 14279,
    predictedPrice: 14567,
    prediksi12Minggu: [14279,14307,14336,14364,14392,14419,14445,14471,14496,14521,14544,14567],
    historicalPrices: [14250,14250],
    perubahanKumulatifPct: 2.23,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 14.058,
    pasarTerhubung: ["Sulawesi Barat", "Jawa Tengah"],
    rekomendasiOperasional: "Harga beras di Sulawesi Selatan diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 3.06). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Sulawesi Selatan — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Sulawesi Selatan diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 3.06). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 3108.8,
    consumption: 1017.1,
  },
  {
    id: "sulawesi-tenggara",
    name: "Sulawesi Tenggara",
    kluster: "C",
    status: "stabil",
    currentPrice: 15730,
    predictedPrice: 16021,
    prediksi12Minggu: [15730,15760,15790,15819,15848,15875,15902,15927,15952,15976,15999,16021],
    historicalPrices: [15700,15700],
    perubahanKumulatifPct: 2.05,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 13.860,
    pasarTerhubung: ["Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Sulawesi Tenggara diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.21). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Rantai distribusi beras di Sulawesi Tenggara lebih panjang dibanding median nasional (nilai 4.00). Petakan seluruh titik perantara dan identifikasi tahapan yang dapat dihilangkan. Fasilitasi skema kemitraan langsung antara penggilingan padi dan jaringan pengecer. Terapkan sistem informasi harga terbuka di tingkat pedagang grosir.",
    recommendation: "Harga beras di Sulawesi Tenggara diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.21). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 379.65,
    consumption: 314.84,
  },
  {
    id: "gorontalo",
    name: "Gorontalo",
    kluster: "A",
    status: "surplus",
    currentPrice: 15282,
    predictedPrice: 16181,
    prediksi12Minggu: [15282,15364,15447,15529,15612,15693,15775,15857,15938,16019,16100,16181],
    historicalPrices: [15200,15200],
    perubahanKumulatifPct: 6.45,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 16.653,
    pasarTerhubung: ["Sulawesi Utara", "Sulawesi Tengah"],
    rekomendasiOperasional: "Harga beras di Gorontalo diprediksi naik 6.5% dalam 3 bulan ke depan, dengan tekanan tertinggi diperkirakan pada awal periode, lalu mereda. Produksi lokal masih mencukupi sebagian besar kebutuhan (surplus ratio 1.06), sehingga tekanan kemungkinan bersumber dari hambatan distribusi atau mekanisme pasar internal. Pasar Sulawesi Utara dan Sulawesi Tengah saat ini masih stabil. Periksa apakah ada penumpukan stok di tingkat distributor. Percepat alur distribusi dari gudang ke pasar eceran dan koordinasikan dengan Bulog wilayah untuk memastikan rantai distribusi internal berjalan lancar. Dengan produksi yang mencukupi, pertimbangkan peran Gorontalo sebagai penyuplai bagi provinsi defisit yang berdekatan — koordinasikan melalui jalur perdagangan aktif.",
    rekomendasiStruktural: "Gorontalo memiliki surplus produksi 0.06 di atas kebutuhan lokal, namun harga beras justru mengalami tekanan kenaikan — indikasi kuat adanya disfungsi dalam tata niaga atau distribusi internal. Lakukan audit menyeluruh dari penggilingan hingga pasar eceran. Evaluasi kemungkinan penguasaan pasar yang tidak sehat oleh segelintir distributor besar, dan perkuat peran lembaga pangan lokal sebagai penyeimbang pasar.",
    recommendation: "Harga beras di Gorontalo diprediksi naik 6.5% dalam 3 bulan ke depan, dengan tekanan tertinggi diperkirakan pada awal periode, lalu mereda. Produksi lokal masih mencukupi sebagian besar kebutuhan (surplus ratio 1.06), sehingga tekanan kemungkinan bersumber dari hambatan distribusi atau mekanisme pasar internal. Pasar Sulawesi Utara dan Sulawesi Tengah saat ini masih stabil.",
    production: 153.77,
    consumption: 144.7,
  },
  {
    id: "sulawesi-barat",
    name: "Sulawesi Barat",
    kluster: "C",
    status: "stabil",
    currentPrice: 14546,
    predictedPrice: 15005,
    prediksi12Minggu: [14546,14592,14638,14682,14726,14769,14811,14852,14892,14930,14968,15005],
    historicalPrices: [14500,14500],
    perubahanKumulatifPct: 3.48,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 12.729,
    pasarTerhubung: ["Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Sulawesi Barat diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.18). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    rekomendasiStruktural: "Sulawesi Barat — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Sulawesi Barat diprediksi stabil dalam 3 bulan ke depan. Produksi lokal mencukupi kebutuhan (surplus ratio 1.18). Pertahankan ritme distribusi yang berjalan. Lakukan pemantauan rutin mingguan.",
    production: 210.92,
    consumption: 178.13,
  },
  {
    id: "maluku",
    name: "Maluku",
    kluster: "D",
    status: "defisit",
    currentPrice: 16895,
    predictedPrice: 17313,
    prediksi12Minggu: [16895,16939,16982,17023,17064,17102,17140,17177,17213,17247,17280,17313],
    historicalPrices: [16800,16850],
    perubahanKumulatifPct: 2.75,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 4.369,
    pasarTerhubung: ["Sulawesi Selatan", "Jawa Tengah"],
    rekomendasiOperasional: "Harga beras di Maluku diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.25, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sulawesi Selatan dan Jawa Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Maluku memiliki konektivitas fisik dengan Jawa Timur dan Sulawesi Tenggara — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Timur dan Sulawesi Tenggara berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Maluku diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.25, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sulawesi Selatan dan Jawa Tengah saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 55.42,
    consumption: 224.58,
  },
  {
    id: "maluku-utara",
    name: "Maluku Utara",
    kluster: "D",
    status: "defisit",
    currentPrice: 17685,
    predictedPrice: 17993,
    prediksi12Minggu: [17685,17719,17752,17784,17815,17844,17872,17899,17925,17949,17971,17993],
    historicalPrices: [17650,17650],
    perubahanKumulatifPct: 1.94,
    shapeTrajectory: "peak_awal",
    skorPrioritas: 10.958,
    pasarTerhubung: ["Sulawesi Utara", "Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Maluku Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.09, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sulawesi Utara dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Maluku Utara memiliki konektivitas fisik dengan Jawa Timur dan Sulawesi Tengah — jalur ini tersedia secara infrastruktur namun belum pernah aktif sebagai jalur perdagangan beras. Saat ini Jawa Timur dan Sulawesi Tengah berada dalam kondisi surplus dan tidak tertekan, sehingga jalur ini berpotensi diaktifkan melalui kebijakan atau insentif distribusi sebagai alternatif pasokan jangka menengah.",
    recommendation: "Harga beras di Maluku Utara diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.09, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sulawesi Utara dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 12.35,
    consumption: 131.18,
  },
  {
    id: "papua-barat",
    name: "Papua Barat",
    kluster: "D",
    status: "defisit",
    currentPrice: 16843,
    predictedPrice: 16865,
    prediksi12Minggu: [16843,16837,16833,16830,16829,16830,16832,16835,16840,16847,16855,16865],
    historicalPrices: [16850,16850],
    perubahanKumulatifPct: 0.09,
    shapeTrajectory: "late_surge",
    skorPrioritas: 9.128,
    pasarTerhubung: ["Papua", "Sulawesi Selatan"],
    rekomendasiOperasional: "Harga beras di Papua Barat diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.07, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Papua dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Rantai distribusi beras di Papua Barat lebih panjang dibanding median nasional (nilai 4.00). Petakan seluruh titik perantara dan identifikasi tahapan yang dapat dihilangkan. Fasilitasi skema kemitraan langsung antara penggilingan padi dan jaringan pengecer. Terapkan sistem informasi harga terbuka di tingkat pedagang grosir.",
    recommendation: "Harga beras di Papua Barat diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.07, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Papua dan Sulawesi Selatan saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 8.36,
    consumption: 116.78,
  },
  {
    id: "papua",
    name: "Papua",
    kluster: "D",
    status: "defisit",
    currentPrice: 19034,
    predictedPrice: 18838,
    prediksi12Minggu: [19034,19018,19001,18985,18968,18950,18932,18914,18896,18877,18858,18838],
    historicalPrices: [19000,19050],
    perubahanKumulatifPct: -1.11,
    shapeTrajectory: "stabil",
    skorPrioritas: 6.917,
    pasarTerhubung: ["Sulawesi Selatan", "Jawa Timur"],
    rekomendasiOperasional: "Harga beras di Papua diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.68, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sulawesi Selatan dan Jawa Timur saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    rekomendasiStruktural: "Papua — tidak ada catatan struktural yang memerlukan perhatian saat ini.",
    recommendation: "Harga beras di Papua diprediksi stabil dalam 3 bulan ke depan, namun dengan surplus ratio 0.68, stabilitas ini bergantung penuh pada kelancaran pasokan dari luar daerah. Pasar Sulawesi Selatan dan Jawa Timur saat ini masih stabil. Gunakan jeda ini untuk memastikan kelancaran distribusi internal. Susun protokol respons darurat untuk skenario gangguan jalur pasokan utama. Diversifikasi sumber pasokan dengan menjalin kesepakatan awal bersama minimal dua provinsi pemasok.",
    production: 195.98,
    consumption: 288.07,
  },
]

// ---------------------------------------------------------------------------
// Lookup maps
// ---------------------------------------------------------------------------

/** Lookup by id */
export const PROVINCE_MAP: Record<string, ProvinceData> = Object.fromEntries(
  PROVINCES.map((p) => [p.id, p])
)

/**
 * Lookup by raw GeoJSON Propinsi key.
 * Key = nilai PERSIS dari field Propinsi di indonesia-provinces.json (huruf kapital, nama lama).
 */
const GEO_NAME_MAP: Record<string, string> = {
  // Sumatera
  "DI. ACEH": "aceh",
  "SUMATERA UTARA": "sumatera-utara",
  "SUMATERA BARAT": "sumatera-barat",
  "RIAU": "riau",
  "KEP. RIAU": "kepulauan-riau",
  "JAMBI": "jambi",
  "SUMATERA SELATAN": "sumatera-selatan",
  "BANGKA BELITUNG": "kepulauan-bangka-belitung",
  "BENGKULU": "bengkulu",
  "LAMPUNG": "lampung",
  // Jawa
  "DKI JAKARTA": "dki-jakarta",
  "JAWA BARAT": "jawa-barat",
  "JAWA TENGAH": "jawa-tengah",
  "DAERAH ISTIMEWA YOGYAKARTA": "di-yogyakarta",
  "JAWA TIMUR": "jawa-timur",
  "PROBANTEN": "banten",          // nama lama Banten di GeoJSON ini
  // Bali & Nusa Tenggara
  "BALI": "bali",
  "NUSATENGGARA BARAT": "nusa-tenggara-barat",
  "NUSA TENGGARA TIMUR": "nusa-tenggara-timur",
  // Kalimantan
  "KALIMANTAN BARAT": "kalimantan-barat",
  "KALIMANTAN TENGAH": "kalimantan-tengah",
  "KALIMANTAN SELATAN": "kalimantan-selatan",
  "KALIMANTAN TIMUR": "kalimantan-timur",
  "KALIMANTAN UTARA": "kalimantan-utara",
  // Sulawesi
  "SULAWESI UTARA": "sulawesi-utara",
  "SULAWESI TENGAH": "sulawesi-tengah",
  "SULAWESI SELATAN": "sulawesi-selatan",
  "SULAWESI TENGGARA": "sulawesi-tenggara",
  "GORONTALO": "gorontalo",
  "SULAWESI BARAT": "sulawesi-barat",
  // Maluku & Papua
  "MALUKU": "maluku",
  "MALUKU UTARA": "maluku-utara",
  "IRIAN JAYA BARAT": "papua-barat",   // nama lama Papua Barat
  "IRIAN JAYA TIMUR": "papua",         // nama lama Papua
}

/**
 * Dipakai IndonesiaMap: lookup ProvinceData dari nama GeoJSON Propinsi.
 */
export const PROVINCE_MAP_BY_GEO: Record<string, ProvinceData> = Object.fromEntries(
  Object.entries(GEO_NAME_MAP)
    .filter(([, id]) => PROVINCE_MAP[id])
    .map(([geoName, id]) => [geoName, PROVINCE_MAP[id]])
)

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

export function formatRupiah(value: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}

export function getNationalSummary() {
  const total = PROVINCES.length
  const surplus = PROVINCES.filter((p) => p.status === "surplus").length
  const stabil = PROVINCES.filter((p) => p.status === "stabil").length
  const defisit = PROVINCES.filter((p) => p.status === "defisit").length
  const avgPrice = Math.round(
    PROVINCES.reduce((sum, p) => sum + p.currentPrice, 0) / total
  )
  return { total, surplus, stabil, defisit, avgPrice }
}

/**
 * Membangun array titik tren harga untuk PriceChart.
 * Menggunakan prediksi_12minggu: minggu 1 = aktual, minggu 2–12 = prediksi.
 */
export function buildTrend(
  province: ProvinceData
): Array<{ week: string; actual?: number; predicted?: number }> {
  const historical = (province.historicalPrices ?? []).map((price, i) => ({
    week: `H-${province.historicalPrices.length - i}`,
    actual: price,
    predicted: undefined,
  }))

  const predicted = province.prediksi12Minggu.map((price, i) => ({
    week: `M${i + 1}`,
    actual: undefined,
    predicted: price,
  }))

  return [...historical, ...predicted]
}
